// Generate an agent-facing Markdown reference for the shipped widget types straight from the widget
// registry (the single source of truth — core/widget.ts metas + any plugin metas). Pure: pass it
// `listMetas()` and it returns the doc string. Surfaced two ways: a "Copy widget reference" button in
// the studio (always current) and a committed docs/widgets.md regenerated by scripts/gen-widget-docs.
// Co-located tests in widgetDocs.test.ts.

import type { ConfigField, WidgetMeta } from './widget';

// Escape a cell value so a literal `|` / newline can't break the Markdown table.
const cell = (s: string): string => s.replace(/\|/g, '\\|').replace(/\n/g, ' ').trim();

const fmtDefault = (v: unknown): string => (v === undefined ? '' : JSON.stringify(v));

// The "options / constraints" column for a field: select options, expr result/target, number range.
function fieldExtra(f: ConfigField): string {
	if (f.kind === 'select') {
		const opts = f.options.length ? f.options.map((o) => `\`${o}\``).join(', ') : '(runtime list)';
		return f.catalog ? `${opts} — from \`${f.catalog}\`` : opts;
	}
	if (f.kind === 'expr') return `→ ${f.result}${f.target ? ` (sets \`${f.target}\`)` : ''}`;
	if (f.kind === 'number') {
		const bits = [
			f.min !== undefined ? `min ${f.min}` : '',
			f.max !== undefined ? `max ${f.max}` : '',
			f.step !== undefined ? `step ${f.step}` : ''
		].filter(Boolean);
		return bits.join(', ');
	}
	return '';
}

function configTable(meta: WidgetMeta): string {
	const fields = meta.configFields ?? [];
	if (!fields.length) return '_No configurable fields._\n';
	const rows = fields.map((f) => {
		const def = fmtDefault(f.default !== undefined ? f.default : meta.defaultConfig?.[f.key]);
		const help = 'help' in f && f.help ? f.help : '';
		return `| \`${f.key}\` | ${f.kind} | ${cell(def)} | ${cell(fieldExtra(f))} | ${cell(help)} |`;
	});
	return [
		'| key | type | default | options / range | description |',
		'| --- | --- | --- | --- | --- |',
		...rows
	].join('\n');
}

function widgetSection(meta: WidgetMeta): string {
	const lines: string[] = [];
	lines.push(`### ${meta.label ?? meta.type} — \`${meta.type}\``);
	// Screenshot (generated by the gallery rig — `npm run gen:shots`). Path is relative to docs/.
	lines.push('', `![${meta.label ?? meta.type} widget](img/widgets/${meta.type}.png)`);
	if (meta.description) lines.push('', meta.description);
	const facts: string[] = [];
	const binds = meta.binds ?? 'scalar';
	facts.push(
		binds === 'none'
			? '- **Sensor:** none (self-sourcing)'
			: `- **Sensor:** binds a \`${binds}\` sensor${
					meta.defaultSensor ? ` (default \`${meta.defaultSensor}\`)` : ''
				}`
	);
	if (meta.defaultSize)
		facts.push(`- **Default size:** ${meta.defaultSize.w}×${meta.defaultSize.h}`);
	if (meta.interactive)
		facts.push('- **Interactive:** catches clicks in passive mode (per-widget click-through)');
	if (meta.intrinsic)
		facts.push('- **Intrinsic size:** `basis:"content"` shrink-wraps to the rendered content');
	lines.push('', ...facts, '', configTable(meta));
	return lines.join('\n');
}

const PREAMBLE = `# Widget reference

> **Generated** from the widget registry — do not hand-edit. Run \`npm run gen:docs\` (in \`client/\`)
> to regenerate, or click **Copy widget reference** in the studio's Widget designer. Source of truth:
> \`client/src/lib/core/widget.ts\` (built-ins) + plugin metas.

This lists every shipped widget **type** and its config schema, so an agent can author layouts
directly. Edit any node's full JSON/YAML in the studio Inspector's **Data** tab (it applies via the
\`replaceNode\` op), or build up the layout JSON below.

## Layout shape

A monitor layout is \`{ root, floating }\`:

- **root** — the in-flow tree: nested **containers** \`{ id, kind: "row" | "col" | "grid", children: [...], gap?, pad?, align?, justify? }\`.
- **floating** — **leaves** placed by an absolute \`rect\` (escape the flow).

A **leaf** wraps one widget instance:

\`\`\`json
{ "id": "gauge-1", "unit": { /* WidgetInstance */ }, "basis": "content" | { "fr": 1 }, "halign": "fill", "valign": "fill" }
\`\`\`

A **WidgetInstance** (\`leaf.unit\`):

\`\`\`json
{ "id": "gauge-1", "type": "gauge", "rect": { "x": 0, "y": 0, "w": 110, "h": 110 },
  "sensor": "cpu.total", "config": { "label": "CPU", "min": 0, "max": 100 }, "css": "/* optional per-instance css */" }
\`\`\`

- \`type\` picks the widget (see below). \`sensor\` binds a sensor id (omit for self-sourcing types).
- \`config\` holds the type's fields (see each widget's table). \`basis: { fr }\` grows along the parent axis; \`"content"\` hugs content; a number/omitted is a fixed/auto size.
- Sensor ids are listed in the studio **Sensors** section (e.g. \`cpu.total\`, \`mem.used\`, \`gpu.util\`, \`net.down\`, \`ha.<entity_id>\`).

## Widgets
`;

/** The full agent-facing widget reference, generated from the given metas (pass `listMetas()`). */
export function widgetReferenceMarkdown(metas: WidgetMeta[]): string {
	const sections = metas.map(widgetSection).join('\n\n');
	return `${PREAMBLE}\n${sections}\n`;
}
